version = 0.1

[default]
[default.global]
[default.global.parameters]
stack_name = "lambda-at-edge-jwt-validation"

[default.build.parameters]
cached = false
parallel = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"
confirm_changeset = false
resolve_s3 = true
no_fail_on_empty_changeset = true
resolve_image_repos = true

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[prod]
[prod.sync]
[prod.sync.parameters]
watch = false